# Configuration for course-management service
course_management:
  host: "0.0.0.0"
  port: 8001
  workers: 1
  timeout: 300
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
  allowed_hosts:
    - "*"
  
  # Service-specific configuration
  description: "Core service for creating, managing, and organizing courses with metadata, structure, and content organization"
  endpoints: ['courses', 'create_course', 'get_course', 'update_course', 'delete_course', 'course_lessons', 'add_lesson', 'get_lesson', 'update_lesson', 'delete_lesson', 'publish_course']
  
  # Database settings
  database:
    pool_size: 10
    max_overflow: 20
    echo: false
  
  # Cache settings
  cache:
    ttl: 3600
    max_size: 1000
