# Configuration for enrollment service
enrollment:
  host: "0.0.0.0"
  port: 8004
  workers: 1
  timeout: 300
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
  allowed_hosts:
    - "*"
  
  # Service-specific configuration
  description: "Service for managing student enrollments, progress tracking, and learning analytics"
  endpoints: ['enroll_student', 'get_enrollment', 'list_enrollments', 'update_enrollment', 'unenroll_student', 'get_student_courses', 'get_course_students', 'update_lesson_progress', 'get_course_progress', 'get_student_progress', 'mark_lesson_complete', 'get_certificates', 'issue_certificate']
  
  # Database settings
  database:
    pool_size: 10
    max_overflow: 20
    echo: false
  
  # Cache settings
  cache:
    ttl: 3600
    max_size: 1000
