server:
  host: 0.0.0.0
  port: 8004
  reload: false

log:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

cors:
  origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
    - "http://localhost:8001"
    - "http://localhost:8003"
    - "http://localhost:8004"
    - "http://${oc.env:HOST_IP,176.9.99.103}:3000"
    - "http://${oc.env:HOST_IP,176.9.99.103}:8000"
    - "http://${oc.env:HOST_IP,176.9.99.103}:8001"
    - "http://${oc.env:HOST_IP,176.9.99.103}:8003"
    - "http://${oc.env:HOST_IP,176.9.99.103}:8004"

database:
  url: postgresql://${oc.env:DB_USER,postgres}:${oc.env:DB_PASSWORD,postgres_password}@${oc.env:DB_HOST,postgres}:${oc.env:DB_PORT,5432}/${oc.env:DB_NAME,course_creator}

jwt:
  secret_key: ${oc.env:JWT_SECRET_KEY,"your-secret-key-here-change-in-production"}
  algorithm: HS256
  token_expiry: 15

service:
  host: 0.0.0.0
  port: 8004
  debug: false
  log_level: INFO

email:
  from_address: ${oc.env:EMAIL_FROM_ADDRESS,"noreply@courseplatform.com"}
  smtp:
    server: ${oc.env:SMTP_SERVER,"localhost"}
    port: ${oc.env:SMTP_PORT,587}
    user: ${oc.env:SMTP_USER,null}
    password: ${oc.env:SMTP_PASSWORD,null}
    use_tls: ${oc.env:SMTP_USE_TLS,true}
  use_mock: ${oc.env:USE_MOCK_EMAIL,false}