# Add this to your main docker-compose.yml:
  test-service:
    build:
      context: .
      dockerfile: services/test-service/Dockerfile
    ports:
      - "${TEST_SERVICE_PORT:-8999}:8999"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./config:/app/config
      - ./shared:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8999/health"]
      interval: 30s
      timeout: 10s
      retries: 3
