services:
  # Shared Base Image for System Package Caching
  base-image:
    image: course-creator-base:latest
    build:
      context: .
      dockerfile: Dockerfile.base
      cache_from:
        - course-creator-base:latest
    # This service only exists to build the base image
    # Other services depend on it being built first
    command: "true"  # Do nothing, just build the image
    profiles: ["build-base"]  # Only run when specifically requested

  # Database Services
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: course_creator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - course-creator-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - course-creator-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Core Microservices
  user-management:
    image: course-creator-user-management:latest
    build:
      context: ./services/user-management
      dockerfile: Dockerfile
      cache_from:
        - course-creator-user-management:latest
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_password@postgres:5432/course_creator
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET_KEY=your-secret-key-change-in-production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_NAME=course_creator
      - ENVIRONMENT=docker
      - DOCKER_CONTAINER=true
      - SERVICE_NAME=user-management
      - LOG_LEVEL=INFO
      - PATH=${VENV_MOUNT_PATH}/bin:$PATH
      - VIRTUAL_ENV=${VENV_MOUNT_PATH}
    volumes:
      - ${VENV_PATH}:${VENV_MOUNT_PATH}:ro
      - /var/log/course-creator:/var/log/course-creator
    ports:
      - "8000:8000"
    networks:
      - course-creator-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; r = requests.get('http://localhost:8000/health'); exit(0 if r.status_code == 200 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  course-generator:
    image: course-creator-course-generator:latest
    build:
      context: ./services/course-generator
      dockerfile: Dockerfile
      cache_from:
        - course-creator-course-generator:latest
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_password@postgres:5432/course_creator
      - REDIS_URL=redis://redis:6379
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - RAG_SERVICE_URL=http://rag-service:8009
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_NAME=course_creator
      - DOCKER_CONTAINER=true
      - SERVICE_NAME=course-generator
      - LOG_LEVEL=INFO
      - ENVIRONMENT=docker
    volumes:
      - ${VENV_PATH}:${VENV_MOUNT_PATH}:ro
      - /var/log/course-creator:/var/log/course-creator
    networks:
      - course-creator-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rag-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; r = requests.get('http://localhost:8001/health'); exit(0 if r.status_code == 200 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  content-storage:
    image: course-creator-content-storage:latest
    build:
      context: ./services/content-storage
      dockerfile: Dockerfile
      cache_from:
        - course-creator-content-storage:latest
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_password@postgres:5432/course_creator
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=docker
      - DOCKER_CONTAINER=true
      - SERVICE_NAME=content-storage
      - LOG_LEVEL=INFO
    ports:
      - "8003:8003"
    volumes:
      - ${VENV_PATH}:${VENV_MOUNT_PATH}:ro
      - content_files:/app/content_files
      - content_storage:/app/storage
      - /var/log/course-creator:/var/log/course-creator
    networks:
      - course-creator-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; r = requests.get('http://localhost:8003/health'); exit(0 if r.status_code == 200 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  course-management:
    image: course-creator-course-management:latest
    build:
      context: ./services/course-management
      dockerfile: Dockerfile
      cache_from:
        - course-creator-course-management:latest
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_password@postgres:5432/course_creator
      - REDIS_URL=redis://redis:6379
      - USER_SERVICE_URL=http://user-management:8000
      - COURSE_GENERATOR_URL=http://course-generator:8001
      - CONTENT_STORAGE_URL=http://content-storage:8003
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_NAME=course_creator
      - ENVIRONMENT=docker
      - DOCKER_CONTAINER=true
      - SERVICE_NAME=course-management
      - LOG_LEVEL=INFO
      # Email Service Configuration
      - USE_MOCK_EMAIL=true
      - SMTP_SERVER=${SMTP_SERVER:-localhost}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - SMTP_USE_TLS=${SMTP_USE_TLS:-true}
    ports:
      - "8004:8004"
    volumes:
      - ${VENV_PATH}:${VENV_MOUNT_PATH}:ro
      - /var/log/course-creator:/var/log/course-creator
    networks:
      - course-creator-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-management:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; r = requests.get('http://localhost:8004/health'); exit(0 if r.status_code == 200 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  content-management:
    image: course-creator-content-management:latest
    build:
      context: ./services/content-management
      dockerfile: Dockerfile
      cache_from:
        - course-creator-content-management:latest
    environment:
      - USER_SERVICE_URL=http://user-management:8000
      - COURSE_GENERATOR_URL=http://course-generator:8001
      - CONTENT_STORAGE_URL=http://content-storage:8003
      - COURSE_MANAGEMENT_URL=http://course-management:8004
      - DATABASE_URL=postgresql://postgres:postgres_password@postgres:5432/course_creator
      - REDIS_URL=redis://redis:6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_NAME=course_creator
      - ENVIRONMENT=docker
      - DOCKER_CONTAINER=true
      - SERVICE_NAME=content-management
      - LOG_LEVEL=INFO
    ports:
      - "8005:8005"
    volumes:
      - ${VENV_PATH}:${VENV_MOUNT_PATH}:ro
      - content_uploads:/app/uploads
      - content_exports:/app/exports
      - template_storage:/app/storage
      - /var/log/course-creator:/var/log/course-creator
    networks:
      - course-creator-network
    depends_on:
      content-storage:
        condition: service_healthy
      course-generator:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; r = requests.get('http://localhost:8005/health'); exit(0 if r.status_code == 200 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # RAG Service - AI Enhancement with ChromaDB
  rag-service:
    image: course-creator-rag-service:latest
    build:
      context: ./services/rag-service
      dockerfile: Dockerfile
      cache_from:
        - course-creator-rag-service:latest
    environment:
      - ENVIRONMENT=docker
      - DOCKER_CONTAINER=true
      - SERVICE_NAME=rag-service
      - LOG_LEVEL=INFO
      - CHROMADB_PATH=/app/chromadb_data
      - LOG_DIR=/var/log/course-creator
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - PATH=${VENV_MOUNT_PATH}/bin:$PATH
      - VIRTUAL_ENV=${VENV_MOUNT_PATH}
    ports:
      - "8009:8009"
    volumes:
      - ${VENV_PATH}:${VENV_MOUNT_PATH}:ro
      - rag_chromadb_data:/app/chromadb_data
      - rag_huggingface_cache:/app/.cache/huggingface
      - /var/log/course-creator:/var/log/course-creator
    networks:
      - course-creator-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; r = requests.get('http://localhost:8009/api/v1/rag/health'); exit(0 if r.status_code == 200 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Analytics Service
  analytics:
    image: course-creator-analytics:latest
    build:
      context: ./services/analytics
      dockerfile: Dockerfile
      cache_from:
        - course-creator-analytics:latest
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_password@postgres:5432/course_creator
      - REDIS_URL=redis://redis:6379
      - USER_SERVICE_URL=http://user-management:8000
      - COURSE_SERVICE_URL=http://course-management:8004
      - LAB_SERVICE_URL=http://lab-manager:8006
      - RAG_SERVICE_URL=http://rag-service:8009
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_NAME=course_creator
      - ENVIRONMENT=docker
      - DOCKER_CONTAINER=true
      - SERVICE_NAME=analytics
      - LOG_LEVEL=INFO
    ports:
      - "8007:8007"
    volumes:
      - ${VENV_PATH}:${VENV_MOUNT_PATH}:ro
      - /var/log/course-creator:/var/log/course-creator
    networks:
      - course-creator-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-management:
        condition: service_healthy
      rag-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; r = requests.get('http://localhost:8007/health'); exit(0 if r.status_code == 200 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Organization Management Service  
  organization-management:
    image: course-creator-organization-management:latest
    build:
      context: ./services/organization-management
      dockerfile: Dockerfile
      cache_from:
        - course-creator-organization-management:latest
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_password@postgres:5432/course_creator
      - REDIS_URL=redis://redis:6379
      - USER_SERVICE_URL=http://user-management:8000
      - COURSE_SERVICE_URL=http://course-management:8004
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_NAME=course_creator
      - ENVIRONMENT=docker
      - DOCKER_CONTAINER=true
      - SERVICE_NAME=organization-management
      - LOG_LEVEL=INFO
      - JWT_SECRET_KEY=your-secret-key-change-in-production
    ports:
      - "8008:8008"
    volumes:
      - ${VENV_PATH}:${VENV_MOUNT_PATH}:ro
      - /var/log/course-creator:/var/log/course-creator
    networks:
      - course-creator-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-management:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; r = requests.get('http://localhost:8008/health'); exit(0 if r.status_code == 200 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Frontend Service
  frontend:
    image: course-creator-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - course-creator-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - course-creator-network
    depends_on:
      - user-management
      - course-management
      - content-management
      - analytics
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Lab Container Management Service
  lab-manager:
    image: course-creator-lab-manager:latest
    build:
      context: ./services/lab-manager
      dockerfile: Dockerfile
      cache_from:
        - course-creator-lab-manager:latest
    environment:
      - LAB_IMAGE_REGISTRY=course-creator/labs
      - MAX_CONCURRENT_LABS=10
      - LAB_SESSION_TIMEOUT=3600
      - DATABASE_URL=postgresql://postgres:postgres_password@postgres:5432/course_creator
      - REDIS_URL=redis://redis:6379
      - RAG_SERVICE_URL=http://rag-service:8009
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_NAME=course_creator
      - ENVIRONMENT=docker
      - DOCKER_CONTAINER=true
      - SERVICE_NAME=lab-containers
      - LOG_LEVEL=INFO
      - LAB_STORAGE_PATH=/home/bbrelin/course-creator/lab-storage
    volumes:
      - ${VENV_PATH}:${VENV_MOUNT_PATH}:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./lab-storage:/home/bbrelin/course-creator/lab-storage
      - /var/log/course-creator:/var/log/course-creator
      - ./config:/home/bbrelin/course-creator/config:ro
    ports:
      - "8006:8006"
    networks:
      - course-creator-network
    depends_on:
      - course-management
      - rag-service
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; r = requests.get('http://localhost:8006/health'); exit(0 if r.status_code == 200 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


volumes:
  postgres_data:
  redis_data:
  content_files:
  content_storage:
  content_uploads:
  content_exports:
  template_storage:
  lab_storage:
  rag_chromadb_data:
  rag_huggingface_cache:

networks:
  course-creator-network:
    driver: bridge