server:
  host: 0.0.0.0
  port: 8001
  reload: false

log:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

cors:
  origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
    - "http://localhost:8001"
    - "http://localhost:8003"
    - "http://localhost:8004"

database:
  url: postgresql+asyncpg://course_user:${DB_PASSWORD}@localhost:5433/course_creator

ai:
  provider: anthropic
  model: claude-3-sonnet-20240229
  api_key: ${ANTHROPIC_API_KEY}
  timeout: 30

service:
  host: 0.0.0.0
  port: 8001
  debug: false
  log_level: INFO