server:
  host: 0.0.0.0
  port: 8003
  reload: false

log:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

cors:
  origins:
    - "https://localhost:3000"
    - "https://localhost:8000"
    - "https://localhost:8001"
    - "https://localhost:8003"
    - "https://localhost:8004"

database:
  host: ${oc.env:DB_HOST,postgres}
  port: ${oc.env:DB_PORT,5432}
  name: ${oc.env:DB_NAME,course_creator}
  username: ${oc.env:DB_USER,postgres}
  password: ${oc.env:DB_PASSWORD,postgres_password}

storage:
  type: local
  path: ./content_files
  max_file_size: 10485760  # 10MB
  allowed_extensions:
    - .pdf
    - .docx
    - .txt
    - .md
    - .mp4
    - .jpg
    - .png

service:
  host: 0.0.0.0
  port: 8003
  debug: false
  log_level: INFO