server:
  host: 0.0.0.0
  port: 8000
  reload: false

log:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

cors:
  origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
    - "http://localhost:8001"
    - "http://localhost:8003"
    - "http://localhost:8004"
    - "http://localhost:8080"
    - "http://176.9.99.103:3000"

database:
  url: postgresql+asyncpg://course_user:${oc.env:DB_PASSWORD}@localhost:5433/course_creator

jwt:
  secret_key: ${oc.env:JWT_SECRET_KEY,"your-secret-key-here-change-in-production"}
  algorithm: HS256
  token_expiry: 15  # Reduced from 30 to 15 minutes for better security

service:
  host: 0.0.0.0
  port: 8000
  debug: false
  log_level: INFO