# User Management Service Configuration
defaults:
  - _self_

# Service configuration
service:
  name: user-management
  host: 0.0.0.0
  port: 8000
  debug: false

# Server configuration (for Uvicorn)
server:
  host: 0.0.0.0
  port: 8000
  reload: false

# Database configuration
database:
  url: postgresql://${oc.env:DB_USER,postgres}:${oc.env:DB_PASSWORD,postgres_password}@${oc.env:DB_HOST,postgres}:${oc.env:DB_PORT,5432}/${oc.env:DB_NAME,course_creator}

# Redis configuration
redis:
  host: ${oc.env:REDIS_HOST,localhost}
  port: ${oc.env:REDIS_PORT,6379}
  db: ${oc.env:REDIS_DB,0}

# CORS configuration
cors:
  origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
    - "http://localhost:8001"
    - "http://localhost:8004"
    - "http://176.9.99.103:3000"
    - "http://176.9.99.103:8000"
    - "http://176.9.99.103:8001"
    - "http://176.9.99.103:8004"

# Logging configuration
log:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# Security
security:
  jwt_secret_key: ${oc.env:JWT_SECRET_KEY}
  jwt_algorithm: HS256
  access_token_expire_minutes: 30

